version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      BUILD_IMAGE: lorf/test-docker-image
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          wdir=$(eval "cd $CIRCLE_WORKING_DIRECTORY && pwd")
          echo "Working directory: $wdir"
          docker run --rm -v "$HOME:$HOME" -u `id -u`:`id -g` -w "$wdir" -i "$BUILD_IMAGE" make
          ls -lR csr-spi-ftdi*
